// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Filters: typeof import('./src/components/home/filters.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    Home: typeof import('./src/components/home/index.vue')['default']
    RoomPark: typeof import('./src/components/home/roomPark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/slider/index.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
  }
}

export {}
